### ISSUE TITLE
403 while running your Quicksilver operation

### ISSUE THREAD

**Issue by pandocs** [pantheon-systems/example-wordpress-composer#35] opened 2017-09-08 00:52 UTC
[pantheon.yml](https://github.com/rachwhitts/pantheon-wp-composer-project/blob/master/pantheon.yml)

Seems like Quicksilver scripts are not installed as expected, sync code workflow for push back to GitHub serves a 403

```
╭─rachel at pantheor.local in [~/sites/pantheon-wp-composer-project]  on git:wp-cfm ✔︎
╰─➤ $ terminus workflow:watch $SITE
 [notice] Watching workflows...
 [notice] Finished workflow 49e63782-940c-11e7-be96-bc764e11bdd3 Sync code on "pr-1" (pr-1) at 2017-09-07 20:37:09
 [notice] ------ Operation: Push changes back to GitHub if needed finished in 1s (pr-1) ------

PANTHEON ERROR:

Expected status 200, got: 403 while running your Quicksilver operation.

Please check your script path is correct and try again.
```

Checked for the `quicksilver-pushback` dir via SFTP but didn't see it:
```
╭─rachel at pantheor.local in [~/sites/pantheon-wp-composer-project]  on git:wp-cfm ✔︎
╰─➤ $ `terminus connection:info $SITE.$ENV --fields='SFTP Command' --format=string`

Connected to appserver.pr-1.56d62883-1e57-41c6-88e7-a6a170bacba1.drush.in.
sftp> cd code/web/private/scripts/quicksilver
sftp> ls -al
-rw-r--r--    1 11804    11804           0 Sep 07 20:02 .gitkeep
sftp>
```

**Comment by rachelwhitton** [comment] 2017-09-08 00:58
Woops, didn't mean to open this while logged in as my docs test user

**Comment by stevector** [comment] 2017-09-08 16:20
Thanks @rachelwhitton! I was able to reproduce this error. It is caused by `quicksilver-pushback` being in `require-dev` instead of `require` and using `--no-dev` here: https://github.com/pantheon-systems/example-wordpress-composer/blob/master/composer.json#L67

My understanding is that we are using `--no-dev` because we don't want dev dependencies in the Live environment. But it is murkier question whether we want dev dependencies on Dev and Multidev environments.

From one perspective, of course we would want dev dependencies on Multidev and Dev. The word is Dev!

But, then at what point would dev dependencies be removed? From the perspective of the git repo on Pantheon we just have commit hashes moving through master and being tagged. In this sense, `--no-dev` is correct because Pantheon's flow does not expect different types of code in different environments, just different points on the same history.

So, here are some options that increase in complexity and go from bad to good and back to bad:

1. Remove `--no-dev` and push everything to Pantheon. I think that's a bad option because using `--no-dev` for Live is a Composer best practice. If we don't honor it then there is little point in splitting them up at all.
2. Stick with `--no-dev` for everything pushed to Pantheon and move `quicksilver-pushback` from `require-dev` to `require.` A pretty easy fix with no much downside beyond having a script used only on multidev be present in all environments. But that's the normal Pantheon way.
3.  Use `--no-dev` only when building the master branch but not for multidev. This opens the door to inconsistency bugs caused by multidevs having different code from Dev -> Test -> Live. It also keeps the WTF of the Dev environment getting `--no-dev`. I'm not certain but I expect we'd need some change in the build tools plugin to handle this option.
4. Automated Hotfix workfow whereby using `--no-dev` just for Test and Live. This would require some kind of messy tag logic. I include just to say that it could be done, not that it should.

I suggest we do option 2 now and open a follow up issue to move `quicksilver-pushback` back to `require-dev` and implement option 3.

**Comment by stevector** [comment] 2018-03-13 21:39
I think I should have closed this issue after https://github.com/pantheon-systems/example-wordpress-composer/pull/41 was merged.

**Closed by stevector** 2018-03-13 21:39 UTC
